//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Generation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DummyTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DummyTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Generation.Resources.DummyTypes", typeof(DummyTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Teshigoto.CompilationTests.DummyTypes;
        ///
        ////// &lt;summary&gt;
        ////// Empty class
        ////// &lt;/summary&gt;
        ///public class EmptyClass
        ///{
        ///}.
        /// </summary>
        internal static string EmptyClass {
            get {
                return ResourceManager.GetString("EmptyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Teshigoto.CompilationTests.DummyTypes
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Empty record class
        ///    /// &lt;/summary&gt;
        ///    public record class EmptyRecordClass
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string EmptyRecordClass {
            get {
                return ResourceManager.GetString("EmptyRecordClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Teshigoto.CompilationTests.DummyTypes
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Empty record struct
        ///    /// &lt;/summary&gt;
        ///    public record struct EmptyRecordStruct
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string EmptyRecordStruct {
            get {
                return ResourceManager.GetString("EmptyRecordStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Teshigoto.CompilationTests.DummyTypes
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Empty struct
        ///    /// &lt;/summary&gt;
        ///    public struct EmptyStruct
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string EmptyStruct {
            get {
                return ResourceManager.GetString("EmptyStruct", resourceCulture);
            }
        }
    }
}
