//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Generation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DummyTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DummyTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Generation.Resources.DummyTypes", typeof(DummyTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Teshigoto.CompilationTests.DummyTypes;
        ///
        ////// &lt;summary&gt;
        ////// Dummy class
        ////// &lt;/summary&gt;
        ///public class DummyClass : IComparable&lt;DummyClass&gt;,
        ///                          IComparable
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    public DummyClass()
        ///    {
        ///    }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;value&quot;&gt;Value&lt;/param&gt;
        ///    public DummyClass(int value)
        ///    {
        ///        Value = value;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyClass {
            get {
                return ResourceManager.GetString("DummyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Teshigoto.CompilationTests.DummyTypes;
        ///
        ////// &lt;summary&gt;
        ////// Dummy record class
        ////// &lt;/summary&gt;
        ///public class DummyRecordClass : IComparable&lt;DummyRecordClass&gt;,
        ///                                IComparable
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    public DummyRecordClass()
        ///    {
        ///    }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;value&quot;&gt;Value&lt;/param&gt;
        ///    public DummyRecordClass(int value)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyRecordClass {
            get {
                return ResourceManager.GetString("DummyRecordClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Teshigoto.CompilationTests.DummyTypes;
        ///
        ////// &lt;summary&gt;
        ////// Dummy class
        ////// &lt;/summary&gt;
        ///public record struct DummyRecordStruct : IComparable&lt;DummyRecordStruct&gt;,
        ///                                         IComparable
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    public DummyRecordStruct()
        ///    {
        ///    }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;value&quot;&gt;Value&lt;/param&gt;
        ///    public DummyRecordStru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyRecordStruct {
            get {
                return ResourceManager.GetString("DummyRecordStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Teshigoto.CompilationTests.DummyTypes;
        ///
        ////// &lt;summary&gt;
        ////// Dummy class
        ////// &lt;/summary&gt;
        ///public struct DummyStruct : IComparable&lt;DummyStruct&gt;,
        ///                            IComparable
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    public DummyStruct()
        ///    {
        ///    }
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;value&quot;&gt;Value&lt;/param&gt;
        ///    public DummyStruct(int value)
        ///    {
        ///        Value = value; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyStruct {
            get {
                return ResourceManager.GetString("DummyStruct", resourceCulture);
            }
        }
    }
}
