//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Generation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Generation.Resources.EquableResources", typeof(EquableResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt; and &lt;see cref=&quot;GeneratorType.Equatable&quot;/&gt; argument
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithExplicitIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore([GeneratorType.Equatable])]
        ///    private int _ignoredFie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithExplicitIgnoreAttribute {
            get {
                return ResourceManager.GetString("ClassWithExplicitIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithExplicitIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.ClassWithExplicitIgnoreAttribute&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithExplicitIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("ClassWithExplicitIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt;
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore]
        ///    private int _ignoredField;
        ///
        ///    #endregion // Fields
        ///
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithIgnoreAttribute {
            get {
                return ResourceManager.GetString("ClassWithIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.ClassWithIgnoreAttribute&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("ClassWithIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with one property
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithOneProperty : IEquatable&lt;ClassWithOneProperty&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;property&quot;&gt;Property&lt;/param&gt;
        ///    public ClassWithOneProperty(int property)
        ///    {
        ///        Property = property;
        ///    }
        ///
        ///    #endregion // Constructor
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithOneProperty {
            get {
                return ResourceManager.GetString("ClassWithOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithOneProperty : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.ClassWithOneProperty&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates whether th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithOnePropertyGenerated {
            get {
                return ResourceManager.GetString("ClassWithOnePropertyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///using Teshigoto.CompilationTests.DummyTypes;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with three properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithThreeProperties : IEquatable&lt;ClassWithThreeProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///    ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithThreeProperties {
            get {
                return ResourceManager.GetString("ClassWithThreeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithThreeProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.ClassWithThreeProperties&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates wh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithThreePropertiesGenerated {
            get {
                return ResourceManager.GetString("ClassWithThreePropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with two properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithTwoProperties : IEquatable&lt;ClassWithTwoProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///    public ClassWithTwoProperties(int propertyOne, string pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithTwoProperties {
            get {
                return ResourceManager.GetString("ClassWithTwoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithTwoProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.ClassWithTwoProperties&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates whethe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithTwoPropertiesGenerated {
            get {
                return ResourceManager.GetString("ClassWithTwoPropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record class with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt; and &lt;see cref=&quot;GeneratorType.Equatable&quot;/&gt; argument
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record class RecordClassWithExplicitIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore([GeneratorType.Equatable])]
        ///    pri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithExplicitIgnoreAttribute {
            get {
                return ResourceManager.GetString("RecordClassWithExplicitIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record class RecordClassWithExplicitIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordClassWithExplicitIgnoreAttribute&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithExplicitIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("RecordClassWithExplicitIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record class with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt;
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record class RecordClassWithIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore]
        ///    private int _ignoredField;
        ///
        ///    #endregion // Fields
        ///
        ///    #region Constructor
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithIgnoreAttribute {
            get {
                return ResourceManager.GetString("RecordClassWithIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record class RecordClassWithIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordClassWithIgnoreAttribute&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::Syst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("RecordClassWithIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record class with one property
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record class RecordClassWithOneProperty : IEquatable&lt;RecordClassWithOneProperty&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;property&quot;&gt;Property&lt;/param&gt;
        ///    public RecordClassWithOneProperty(int property)
        ///    {
        ///        Property = property;
        ///    }
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithOneProperty {
            get {
                return ResourceManager.GetString("RecordClassWithOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record class RecordClassWithOneProperty : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordClassWithOneProperty&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::System.CodeD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithOnePropertyGenerated {
            get {
                return ResourceManager.GetString("RecordClassWithOnePropertyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///using Teshigoto.CompilationTests.DummyTypes;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record class with three properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record class RecordClassWithThreeProperties : IEquatable&lt;RecordClassWithThreeProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithThreeProperties {
            get {
                return ResourceManager.GetString("RecordClassWithThreeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record class RecordClassWithThreeProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordClassWithThreeProperties&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::Syst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithThreePropertiesGenerated {
            get {
                return ResourceManager.GetString("RecordClassWithThreePropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record class with two properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record class RecordClassWithTwoProperties : IEquatable&lt;RecordClassWithTwoProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///    public RecordClassWithTwoPrope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithTwoProperties {
            get {
                return ResourceManager.GetString("RecordClassWithTwoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record class RecordClassWithTwoProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordClassWithTwoProperties&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::System.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordClassWithTwoPropertiesGenerated {
            get {
                return ResourceManager.GetString("RecordClassWithTwoPropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record struct with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt; and &lt;see cref=&quot;GeneratorType.Equatable&quot;/&gt; argument
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record struct RecordStructWithExplicitIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore([GeneratorType.Equatable])]
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithExplicitIgnoreAttribute {
            get {
                return ResourceManager.GetString("RecordStructWithExplicitIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record struct RecordStructWithExplicitIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordStructWithExplicitIgnoreAttribute&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithExplicitIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("RecordStructWithExplicitIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record struct with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt;
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record struct RecordStructWithIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore]
        ///    private int _ignoredField;
        ///
        ///    #endregion // Fields
        ///
        ///    #region Constructor
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithIgnoreAttribute {
            get {
                return ResourceManager.GetString("RecordStructWithIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record struct RecordStructWithIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordStructWithIgnoreAttribute&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("RecordStructWithIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record struct with one property
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record struct RecordStructWithOneProperty : IEquatable&lt;RecordStructWithOneProperty&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;property&quot;&gt;Property&lt;/param&gt;
        ///    public RecordStructWithOneProperty(int property)
        ///    {
        ///        Property = property;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithOneProperty {
            get {
                return ResourceManager.GetString("RecordStructWithOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record struct RecordStructWithOneProperty : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordStructWithOneProperty&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::System.Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithOnePropertyGenerated {
            get {
                return ResourceManager.GetString("RecordStructWithOnePropertyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///using Teshigoto.CompilationTests.DummyTypes;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record struct with three properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record struct RecordStructWithThreeProperties : IEquatable&lt;RecordStructWithThreeProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithThreeProperties {
            get {
                return ResourceManager.GetString("RecordStructWithThreeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record struct RecordStructWithThreeProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordStructWithThreeProperties&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithThreePropertiesGenerated {
            get {
                return ResourceManager.GetString("RecordStructWithThreePropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Record struct with two properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial record struct RecordStructWithTwoProperties : IEquatable&lt;RecordStructWithTwoProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///    public RecordStructWithTwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithTwoProperties {
            get {
                return ResourceManager.GetString("RecordStructWithTwoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial record struct RecordStructWithTwoProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.RecordStructWithTwoProperties&gt;
        ///{
        ///    /// &lt;inheritdoc /&gt;
        ///    [global::Syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecordStructWithTwoPropertiesGenerated {
            get {
                return ResourceManager.GetString("RecordStructWithTwoPropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Struct with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt; and &lt;see cref=&quot;GeneratorType.Equatable&quot;/&gt; argument
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial struct StructWithExplicitIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore([GeneratorType.Equatable])]
        ///    private int _ignored [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithExplicitIgnoreAttribute {
            get {
                return ResourceManager.GetString("StructWithExplicitIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial struct StructWithExplicitIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.StructWithExplicitIgnoreAttribute&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithExplicitIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("StructWithExplicitIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Struct with &lt;see cref=&quot;IgnoreAttribute&quot;/&gt;
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial struct StructWithIgnoreAttribute
        ///{
        ///    #region Fields
        ///
        ///    /// &lt;summary&gt;
        ///    /// Field
        ///    /// &lt;/summary&gt;
        ///    private int _field;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Ignored field
        ///    /// &lt;/summary&gt;
        ///    [Ignore]
        ///    private int _ignoredField;
        ///
        ///    #endregion // Fields
        ///
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithIgnoreAttribute {
            get {
                return ResourceManager.GetString("StructWithIgnoreAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial struct StructWithIgnoreAttribute : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithIgnoreAttributeGenerated {
            get {
                return ResourceManager.GetString("StructWithIgnoreAttributeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Struct with one property
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial struct StructWithOneProperty : IEquatable&lt;StructWithOneProperty&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;property&quot;&gt;Property&lt;/param&gt;
        ///    public StructWithOneProperty(int property)
        ///    {
        ///        Property = property;
        ///    }
        ///
        ///    #endregion // Construct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithOneProperty {
            get {
                return ResourceManager.GetString("StructWithOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial struct StructWithOneProperty : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.StructWithOneProperty&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates whether [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithOnePropertyGenerated {
            get {
                return ResourceManager.GetString("StructWithOnePropertyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///using Teshigoto.CompilationTests.DummyTypes;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Struct with three properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial struct StructWithThreeProperties : IEquatable&lt;StructWithThreeProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithThreeProperties {
            get {
                return ResourceManager.GetString("StructWithThreeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial struct StructWithThreeProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.StructWithThreeProperties&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithThreePropertiesGenerated {
            get {
                return ResourceManager.GetString("StructWithThreePropertiesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Struct with two properties
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial struct StructWithTwoProperties : IEquatable&lt;StructWithTwoProperties&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;propertyOne&quot;&gt;Property 1&lt;/param&gt;
        ///    /// &lt;param name=&quot;propertyTwo&quot;&gt;Property 2&lt;/param&gt;
        ///    public StructWithTwoProperties(int propertyOne, stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithTwoProperties {
            get {
                return ResourceManager.GetString("StructWithTwoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial struct StructWithTwoProperties : global::System.IEquatable&lt;global::Teshigoto.CompilationTests.Equable.StructWithTwoProperties&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructWithTwoPropertiesGenerated {
            get {
                return ResourceManager.GetString("StructWithTwoPropertiesGenerated", resourceCulture);
            }
        }
    }
}
