//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Generation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Generation.Resources.MapperResources", typeof(MapperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.UnitTests;
        ///
        ///public class MapperSource
        ///{
        ///    public int Value1 { get; set; }
        ///    public int Value2 { get; set; }
        ///    public int IntValue { get; set; }
        ///    public long LongValue { get; set; }
        ///    public decimal DecimalValue { get; set; }
        ///}
        ///
        ///public class MapperDestination
        ///{
        ///    public int Value1 { get; set; }
        ///    public int Value2 { get; set; }
        ///    public long LongValue { get; set; }
        ///    public int IntValue { get; set; }
        ///    public float Float [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.UnitTests;
        ///
        ///public class MapperSource
        ///{
        ///    public int Value1 { get; set; }
        ///    public int Value2 { get; set; }
        ///    public int IntValue { get; set; }
        ///    public long LongValue { get; set; }
        ///    public decimal DecimalValue { get; set; }
        ///}
        ///
        ///public class MapperDestination
        ///{
        ///    public int Value1 { get; set; }
        ///    public int Value2 { get; set; }
        ///    public long LongValue { get; set; }
        ///    public int IntValue { get; set; }
        ///    public float Float [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingExtension {
            get {
                return ResourceManager.GetString("MappingExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.UnitTests;
        ///
        ///public partial class MapperExtensions
        ///{
        ///    public static partial void Extension(this global::Teshigoto.UnitTests.MapperSource source, ref global::Teshigoto.UnitTests.MapperDestination destination)
        ///    {
        ///        destinat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingExtensionGenerated {
            get {
                return ResourceManager.GetString("MappingExtensionGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.UnitTests;
        ///
        ///public partial class Mapper
        ///{
        ///    public static partial void Static(global::Teshigoto.UnitTests.MapperSource source, global::Teshigoto.UnitTests.MapperDestination destination)
        ///    {
        ///        destination.Value1 = source.Va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MappingGenerated {
            get {
                return ResourceManager.GetString("MappingGenerated", resourceCulture);
            }
        }
    }
}
