//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Generation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProxyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProxyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Generation.Resources.ProxyResources", typeof(ProxyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma warning disable CS0067
        ///#pragma warning disable SA1402
        ///
        ///using System;
        ///
        ///using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Proxy;
        ///
        ////// &lt;summary&gt;
        ////// Test base interface to be proxied
        ////// &lt;/summary&gt;
        ///internal interface IInterfaceBase
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Event
        ///    /// &lt;/summary&gt;
        ///    event EventHandler&lt;EventArgs&gt; BaseEvent;
        ///
        ///    /// &lt;summary&gt;
        ///    /// Property with only a getter
        ///    /// &lt;/summary&gt;
        ///    string? BaseProperty0 { get; }
        ///
        ///    /// &lt;summary&gt;
        ///    ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: $$CURRENT_VERSION$$
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Proxy;
        ///
        ///#region _IProxy
        ///
        ////// &lt;summary&gt;
        ////// Internal proxy interface
        ////// &lt;/summary&gt;
        ///[global::System.CodeDom.Compiler.GeneratedCodeAttribute(&quot;Teshigoto.Generators&quot;, &quot;$$CURRENT_VERSION$$&quot;)]
        ///file interface _IProxy
        ///{
        ///    /// &lt;su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassGenerated {
            get {
                return ResourceManager.GetString("ClassGenerated", resourceCulture);
            }
        }
    }
}
