//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teshigoto.UnitTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EquableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teshigoto.UnitTests.Resources.EquableResources", typeof(EquableResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Teshigoto.Annotation;
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ////// &lt;summary&gt;
        ////// Class with one property
        ////// &lt;/summary&gt;
        ///[Equable]
        ///internal partial class ClassWithOneProperty : IEquatable&lt;ClassWithOneProperty&gt;
        ///{
        ///    #region Constructor
        ///
        ///    /// &lt;summary&gt;
        ///    /// Constructor
        ///    /// &lt;/summary&gt;
        ///    /// &lt;param name=&quot;property&quot;&gt;Property&lt;/param&gt;
        ///    public ClassWithOneProperty(int property)
        ///    {
        ///        Property = property;
        ///    }
        ///
        ///    #endregion // Constructor
        ///
        ///    #region Properti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithOneProperty {
            get {
                return ResourceManager.GetString("ClassWithOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;
        /////     This code was generated by Teshigoto.Generators.
        /////     Version: 1.0.0.0
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///
        ///#nullable enable
        ///
        ///namespace Teshigoto.CompilationTests.Equable;
        ///
        ///internal partial class ClassWithOneProperty : global::System.IEquatable&lt;ClassWithOneProperty&gt;
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Returns a value that indicates whether the values of two &lt;see cref=&quot;Teshigoto.CompilationT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassWithOnePropertyGenerated {
            get {
                return ResourceManager.GetString("ClassWithOnePropertyGenerated", resourceCulture);
            }
        }
    }
}
