// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: $$CURRENT_VERSION$$
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Comparable;

partial struct StructWithThreeProperties : global::System.IComparable<global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties>, global::System.IComparable
{
    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value is less than another <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is less than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator <(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties left, global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties right)
    {
        return left.CompareTo(right) < 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value is less than or equal to another <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, false.</returns>
    public static bool operator <=(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties left, global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties right)
    {
        return left.CompareTo(right) <= 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value is greater than another <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator >(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties left, global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties right)
    {
        return left.CompareTo(right) > 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value is greater than or equal to another <see cref="T:global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator >=(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties left, global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties right)
    {
        return left.CompareTo(right) >= 0;
    }

    /// <inheritdoc/>
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (obj is global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties other)
        {
            return CompareTo(other);
        }

        throw new global::System.ArgumentException($"Object must be of type {nameof(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties)}");
    }

    /// <inheritdoc/>
    public int CompareTo(global::Teshigoto.CompilationTests.Comparable.StructWithThreeProperties other)
    {
        if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(PropertyOne, other.PropertyOne) == false)
        {
            return global::System.Collections.Generic.Comparer<int>.Default.Compare(PropertyOne, other.PropertyOne);
        }

        if (global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(PropertyTwo, other.PropertyTwo) == false)
        {
            return global::System.Collections.Generic.Comparer<string>.Default.Compare(PropertyTwo, other.PropertyTwo);
        }

        return global::System.Collections.Generic.Comparer<global::Teshigoto.CompilationTests.DummyTypes.DummyStruct?>.Default.Compare(PropertyThree, other.PropertyThree);
    }
}