// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: $$CURRENT_VERSION$$
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Equable;

internal partial record struct RecordStructWithExplicitIgnoreAttribute : global::System.IEquatable<global::Teshigoto.CompilationTests.Equable.RecordStructWithExplicitIgnoreAttribute>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public bool Equals(global::Teshigoto.CompilationTests.Equable.RecordStructWithExplicitIgnoreAttribute other)
    {
        return global::System.Collections.Generic.EqualityComparer<global::System.Int32>.Default.Equals(this._field, other._field)
               && global::System.Collections.Generic.EqualityComparer<global::System.Int32>.Default.Equals(this.Property, other.Property);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(this._field);
        hash.Add(this.Property);

        return hash.ToHashCode();
    }
}