// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: $$CURRENT_VERSION$$
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Equable;

internal partial struct StructWithIgnoreAttribute : global::System.IEquatable<global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute>
{
    /// <summary>
    /// Returns a value that indicates whether the values of two <see cref="global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute"/> objects are equal.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if the <paramref name="left"/> and <paramref name="right"/> parameters have the same value; otherwise, false.</returns>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public static bool operator ==(global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute left, global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute right)
    {
        return left.Equals(right);
    }

    /// <summary>
    /// Returns a value that indicates whether the values of two <see cref="global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute"/> objects have different values.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left"/> and <paramref name="right"/> are not equal; otherwise, false.</returns>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public static bool operator !=(global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute left, global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute right)
    {
        return left.Equals(right) == false;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public override bool Equals(object? obj)
    {
        return obj is global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute other
               && Equals(other);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public bool Equals(global::Teshigoto.CompilationTests.Equable.StructWithIgnoreAttribute other)
    {
        return global::System.Collections.Generic.EqualityComparer<global::System.Int32>.Default.Equals(this._field, other._field)
               && global::System.Collections.Generic.EqualityComparer<global::System.Int32>.Default.Equals(this.Property, other.Property);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "$$CURRENT_VERSION$$")]
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(this._field);
        hash.Add(this.Property);

        return hash.ToHashCode();
    }
}