// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Proxy;

#region _IProxy

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "1.0.0.0")]
file interface _IProxy
{
    /// <summary>
    /// Implementation
    /// </summary>
    public global::Teshigoto.CompilationTests.Proxy.IInterface Implementation { get; set; }
}

#endregion // IProxy

#region _Resolver

/// <summary>
/// Temporary implementation to intercept the calls to resolve the implementation object
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "1.0.0.0")]
file class _Resolver : global::Teshigoto.CompilationTests.Proxy.IInterface
{
    #region Fields

    /// <summary>
    /// Proxy assigned to the resolver
    /// </summary>
    private _IProxy _proxy;

    #endregion // Fields

    #region Constructor

    /// <summary>
    /// Constructor
    /// </summary>
    /// <param name="proxy">Proxy object</param>
    public _Resolver(_IProxy proxy)
    {
        _proxy = proxy;
    }

    #endregion // Constructor

    #region Methods

    /// <summary>
    /// Resolving the implementation object
    /// </summary>
    private void Resolve()
    {
        lock (this)
        {
            _proxy.Implementation ??= new global::Teshigoto.CompilationTests.Proxy.Class();
        }
    }

    #endregion // Methods

    #region global::Teshigoto.CompilationTests.Proxy.IInterface

    /// <inheritdoc />
    void global::Teshigoto.CompilationTests.Proxy.IInterface.MethodVoid(string value0, ref string value1, out string value2)
    {
        Resolve();

        _proxy.Implementation.MethodVoid(value0, ref value1, out value2);
    }

    /// <inheritdoc />
    string global::Teshigoto.CompilationTests.Proxy.IInterface.MethodString()
    {
        Resolve();

        return _proxy.Implementation.MethodString();
    }

    /// <inheritdoc />
    string global::Teshigoto.CompilationTests.Proxy.IInterface.Property0
    {
        get
        {
            Resolve();

            return _proxy.Implementation.Property0;
        }
    }

    /// <inheritdoc />
    string global::Teshigoto.CompilationTests.Proxy.IInterface.Property1
    {
        set
        {
            Resolve();

            _proxy.Implementation.Property1 = value;
        }
    }

    /// <inheritdoc />
    string global::Teshigoto.CompilationTests.Proxy.IInterface.Property2
    {
        get
        {
            Resolve();

            return _proxy.Implementation.Property2;
        }
        set
        {
            Resolve();

            _proxy.Implementation.Property2 = value;
        }
    }

    /// <inheritdoc />
    event global::System.EventHandler<global::System.EventArgs> global::Teshigoto.CompilationTests.Proxy.IInterface.Event
    {
        add
        {
            Resolve();

            _proxy.Implementation.Event += value;
        }
        remove
        {
            Resolve();

            _proxy.Implementation.Event += value;
        }
    }

    #endregion // global::Teshigoto.CompilationTests.Proxy.IInterface

    #region global::Teshigoto.CompilationTests.Proxy.IInterfaceBase

    /// <inheritdoc />
    void global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseMethodVoid(string? value0, ref string? value1, out string? value2)
    {
        Resolve();

        _proxy.Implementation.BaseMethodVoid(value0, ref value1, out value2);
    }

    /// <inheritdoc />
    string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseMethodString()
    {
        Resolve();

        return _proxy.Implementation.BaseMethodString();
    }

    /// <inheritdoc />
    string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty0
    {
        get
        {
            Resolve();

            return _proxy.Implementation.BaseProperty0;
        }
    }

    /// <inheritdoc />
    string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty1
    {
        set
        {
            Resolve();

            _proxy.Implementation.BaseProperty1 = value;
        }
    }

    /// <inheritdoc />
    string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty2
    {
        get
        {
            Resolve();

            return _proxy.Implementation.BaseProperty2;
        }
        set
        {
            Resolve();

            _proxy.Implementation.BaseProperty2 = value;
        }
    }

    /// <inheritdoc />
    event global::System.EventHandler<global::System.EventArgs> global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseEvent
    {
        add
        {
            Resolve();

            _proxy.Implementation.BaseEvent += value;
        }
        remove
        {
            Resolve();

            _proxy.Implementation.BaseEvent += value;
        }
    }

    #endregion // global::Teshigoto.CompilationTests.Proxy.IInterfaceBase
}

#endregion // _Resolver

internal partial class Class
{
    /// <summary>
    /// Proxy of <see cref="global::Teshigoto.CompilationTests.Proxy.Class"/> which implements <see cref="global::Teshigoto.CompilationTests.Proxy.IInterface"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "1.0.0.0")]
    internal class Proxy : global::Teshigoto.CompilationTests.Proxy.IInterface,
                           _IProxy
    {
        #region Fields

        /// <summary>
        /// Implementation of <see cref="global::Teshigoto.CompilationTests.Proxy.IInterface"/>
        /// </summary>
        private global::Teshigoto.CompilationTests.Proxy.IInterface _implementation;

        #endregion // Fields

        #region Constructor

        /// <summary>
        /// Constructor
        /// </summary>
        public Proxy()
        {
            _implementation = new _Resolver(this);
        }

        #endregion // Constructor

        #region _IProxy

        /// <inheritdoc />
        global::Teshigoto.CompilationTests.Proxy.IInterface _IProxy.Implementation
        {
            get => _implementation;
            set => _implementation = value;
        }

        #endregion // _IProxy

        #region global::Teshigoto.CompilationTests.Proxy.IInterface

        /// <inheritdoc />
        void global::Teshigoto.CompilationTests.Proxy.IInterface.MethodVoid(string value0, ref string value1, out string value2)
        {
            _implementation.MethodVoid(value0, ref value1, out value2);
        }

        /// <inheritdoc />
        string global::Teshigoto.CompilationTests.Proxy.IInterface.MethodString()
        {
            return _implementation.MethodString();
        }

        /// <inheritdoc />
        string global::Teshigoto.CompilationTests.Proxy.IInterface.Property0
        {
            get => _implementation.Property0;
        }

        /// <inheritdoc />
        string global::Teshigoto.CompilationTests.Proxy.IInterface.Property1
        {
            set => _implementation.Property1 = value;
        }

        /// <inheritdoc />
        string global::Teshigoto.CompilationTests.Proxy.IInterface.Property2
        {
            get => _implementation.Property2;
            set => _implementation.Property2 = value;
        }

        /// <inheritdoc />
        event global::System.EventHandler<global::System.EventArgs> global::Teshigoto.CompilationTests.Proxy.IInterface.Event
        {
            add => _implementation.Event += value;
            remove => _implementation.Event += value;
        }

        #endregion // global::Teshigoto.CompilationTests.Proxy.IInterface

        #region global::Teshigoto.CompilationTests.Proxy.IInterfaceBase

        /// <inheritdoc />
        void global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseMethodVoid(string? value0, ref string? value1, out string? value2)
        {
            _implementation.BaseMethodVoid(value0, ref value1, out value2);
        }

        /// <inheritdoc />
        string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseMethodString()
        {
            return _implementation.BaseMethodString();
        }

        /// <inheritdoc />
        string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty0
        {
            get => _implementation.BaseProperty0;
        }

        /// <inheritdoc />
        string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty1
        {
            set => _implementation.BaseProperty1 = value;
        }

        /// <inheritdoc />
        string? global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseProperty2
        {
            get => _implementation.BaseProperty2;
            set => _implementation.BaseProperty2 = value;
        }

        /// <inheritdoc />
        event global::System.EventHandler<global::System.EventArgs> global::Teshigoto.CompilationTests.Proxy.IInterfaceBase.BaseEvent
        {
            add => _implementation.BaseEvent += value;
            remove => _implementation.BaseEvent += value;
        }

        #endregion // global::Teshigoto.CompilationTests.Proxy.IInterfaceBase
    }
}