// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 0.1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Mapper;

public partial class MapperDestination
{
    public partial MapperDestination(global::Teshigoto.CompilationTests.Mapper.MapperSource source)
    {
        this.Value1 = source.Value1;
        this.Value2 = source.Value2;
        this.LongValue = source.IntValue;
        this.IntValue = (int)source.LongValue;
        this.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void Assign(global::Teshigoto.CompilationTests.Mapper.MapperSource source)
    {
        this.Value1 = source.Value1;
        this.Value2 = source.Value2;
        this.LongValue = source.IntValue;
        this.IntValue = (int)source.LongValue;
        this.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }
}