// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Mapper;

public partial class Mapper
{
    public static partial void Map(global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void Instance(global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void RefSource(ref global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void InSource(in global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void RefReadonlySource(ref readonly global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }

    public partial void RefDestination(global::Teshigoto.CompilationTests.Mapper.MapperSource source, ref global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value = source.Value;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }
}