// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Mapper;

internal partial class MapperExtensions
{
    public static partial void Map(this global::Teshigoto.CompilationTests.Mapper.MapperSource source, global::Teshigoto.CompilationTests.Mapper.MapperDestination destination)
    {
        destination.Value1 = source.Value1;
        destination.Value2 = source.Value2;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.CompilationTests.Mapper.DecimalConverter.Convert(source.DecimalValue);
    }
}