// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: $$CURRENT_VERSION$$
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.UnitTests;

public partial class MapperExtensions
{
    public static partial void Extension(this global::Teshigoto.UnitTests.MapperSource source, global::Teshigoto.UnitTests.MapperDestination destination)
    {
        destination.Value1 = source.Value1;
        destination.Value2 = source.Value2;
        destination.LongValue = source.IntValue;
        destination.IntValue = (int)source.LongValue;
        destination.FloatValue = global::Teshigoto.UnitTests.DecimalConverter.Convert(source.DecimalValue);
    }
}