// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.UnitTests;

public partial class Mapper
{
    public static partial void Map(in global::Teshigoto.UnitTests.MapperSource source, in global::Teshigoto.UnitTests.MapperDestination destination)
    {
        destination.Value = source.Value;
    }
}