// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 0.1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Comparable;

partial class ClassWithExplicitIgnoreAttribute : global::System.IComparable<global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute>, global::System.IComparable
{
    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value is less than another <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is less than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator <(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? left, global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? right)
    {
        return global::System.Collections.Generic.Comparer<global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute>.Default.Compare(left, right) < 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value is less than or equal to another <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, false.</returns>
    public static bool operator <=(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? left, global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? right)
    {
        return global::System.Collections.Generic.Comparer<global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute>.Default.Compare(left, right) <= 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value is greater than another <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator >(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? left, global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? right)
    {
        return global::System.Collections.Generic.Comparer<global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute>.Default.Compare(left, right) > 0;
    }

    /// <summary>
    /// Returns a value that indicates whether a <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value is greater than or equal to another <see cref="T:global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute" /> value.
    /// </summary>
    /// <param name="left">The first value to compare.</param>
    /// <param name="right">The second value to compare.</param>
    /// <returns>true if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, false.</returns>
    public static bool operator >=(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? left, global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? right)
    {
        return global::System.Collections.Generic.Comparer<global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute>.Default.Compare(left, right) >= 0;
    }

    /// <inheritdoc/>
    public int CompareTo(object? obj)
    {
        if (obj is null)
        {
            return 1;
        }

        if (ReferenceEquals(this, obj))
        {
            return 0;
        }

        if (obj is global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute other)
        {
            return CompareTo(other);
        }

        throw new global::System.ArgumentException($"Object must be of type {nameof(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute)}");
    }

    /// <inheritdoc/>
    public int CompareTo(global::Teshigoto.CompilationTests.Comparable.ClassWithExplicitIgnoreAttribute? other)
    {
        if (other is null)
        {
            return 1;
        }

        if (ReferenceEquals(this, other))
        {
            return 0;
        }

        if (global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_field, other._field) == false)
        {
            return global::System.Collections.Generic.Comparer<int>.Default.Compare(_field, other._field);
        }

        return global::System.Collections.Generic.Comparer<int>.Default.Compare(Property, other.Property);
    }
}