// <auto-generated>
//     This code was generated by Teshigoto.Generators.
//     Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

namespace Teshigoto.CompilationTests.Equable;

internal partial record struct RecordStructWithThreeProperties : global::System.IEquatable<global::Teshigoto.CompilationTests.Equable.RecordStructWithThreeProperties>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "1.0.0.0")]
    public bool Equals(global::Teshigoto.CompilationTests.Equable.RecordStructWithThreeProperties other)
    {
        return global::System.Collections.Generic.EqualityComparer<global::System.Int32>.Default.Equals(this.PropertyOne, other.PropertyOne)
               && global::System.Collections.Generic.EqualityComparer<global::System.String>.Default.Equals(this.PropertyTwo, other.PropertyTwo)
               && global::System.Collections.Generic.EqualityComparer<global::Teshigoto.CompilationTests.DummyTypes.DummyRecordStruct?>.Default.Equals(this.PropertyThree, other.PropertyThree);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Teshigoto.Generators", "1.0.0.0")]
    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();

        hash.Add(this.PropertyOne);
        hash.Add(this.PropertyTwo);
        hash.Add(this.PropertyThree);

        return hash.ToHashCode();
    }
}